Repository YiGu-Studio/Documentation, pull requests merged in 2020-04, with the labels that each got.

#21 translated submodule.md
  _xmldocs/submodule.md
Labels: enhancement

#26 Link fix
  _intro/getting-started.md
Labels: bug

#24 #15 Translated missionbehaviour.md
  c-api-documentation/mountandblade/missionbehaviour.md
Labels: enhancement

#37 Translated input.md
  c-api-documentation/inputsystem/input.md
Labels: enhancement

#38 Module info translated
  c-api-documentation/library/moduleinfo.md
Labels: enhancement

#41 Gamemenu.md translated
  _csharp-api/campaignsystem/gamemenu.md
Labels: enhancement

#40 Screen base.md translated
  _gauntlet/screenbase.md
Labels: enhancement

#39 Screen manager translated
  _gauntlet/screenmanager.md
Labels: enhancement

#43 Rebase from master 04 10
  SUMMARY.md
  _csharp-api/campaignsystem/settlement.md
  _tutorials/packing_mods_for_vortex.md
  c-api-documentation/engine/scene.md
Labels: documentation

#44 Translate scene.md
  c-api-documentation/engine/scene.md
Labels: enhancement

#50 add missing files
  _csharp-api/core/README.md
  _csharp-api/core/itemobject.md
  _csharp-api/core/mbobjectmanager.md
  _csharp-api/engine/README.md
  _csharp-api/engine/gameentity.md
  _csharp-api/engine/globallayer.md
  _csharp-api/engine/scene.md
  _csharp-api/engine/scriptcomponentbehaviour.md
  _csharp-api/library/README.md
  _csharp-api/library/moduleinfo.md
  _csharp-api/mountandblade/agent.md
  _csharp-api/mountandblade/mbinitialscreenbase.md
  _csharp-api/mountandblade/mission.md
  _csharp-api/mountandblade/team.md
Labels: bug

#54 Update README.md
  README.md
Labels: bug

#55 translated NPCCharacter README.md
  _xmldocs/NPCCharacters/NPCCharacter/README.md
Labels: enhancement
